# Generated by Django 4.0.6 on 2022-10-03 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mosh', '0002_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Phone',
            new_name='phone',
        ),
    ]
