# Generated by Django 4.0.6 on 2022-10-18 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mosh', '0007_employee_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('view_history', 'Can View History')]},
        ),
    ]
