# Generated by Django 4.0.6 on 2022-09-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('buying_price', models.FloatField(null=True)),
                ('max_offer_price', models.FloatField(null=True)),
                ('qty', models.IntegerField(null=True)),
            ],
        ),
    ]
