# Generated by Django 4.0.6 on 2022-07-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='procut_image',
            field=models.ManyToManyField(null=True, to='common.productimage'),
        ),
    ]
