# Generated by Django 4.0.6 on 2022-07-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_productimage_product_procut_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='procut_image',
            field=models.ManyToManyField(to='common.productimage'),
        ),
    ]
